# 当有提交推送到仓库时触发
# 利用缓存加快构建速度，并上传构建产物
name: 构建-提交

on:
  push:
    branches:
      - dev

jobs:
  build:
    runs-on: ubuntu-latest
    environment: staging

    steps:
      - name: 提取当前分支名称
        shell: bash
        # bash 模式扩展，获取不带斜杠的分支名
        run: ref="${GITHUB_REF#refs/heads/}" && echo "branch=${ref////-}" >> $GITHUB_OUTPUT
        id: ref

      - name: 检出源代码
        uses: actions/checkout@v4

      - name: 设置 Java 21
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 21

      - name: 设置 Gradle
        uses: gradle/actions/setup-gradle@v4
        with:
          cache-read-only: false

      - name: 执行 Gradle 构建
        run: ./gradlew build

      - name: 上传构建产物
        uses: actions/upload-artifact@v4
        with:
          name: sodium-构建产物-${{ steps.ref.outputs.branch }}
          path: build/mods/*.jar

      - name: 发布快照版本到 CaffeineMC Maven 仓库
        env:
          ORG_GRADLE_PROJECT_caffeineMCMavenUsername: ${{ secrets.CAFFEINEMC_MAVEN_USERNAME }}
          ORG_GRADLE_PROJECT_caffeineMCMavenPassword: ${{ secrets.CAFFEINEMC_MAVEN_PASSWORD }}
        if: ${{ env.ORG_GRADLE_PROJECT_caffeineMCMavenUsername != '' && env.ORG_GRADLE_PROJECT_caffeineMCMavenPassword != '' }}
        run: ./gradlew publishAllPublicationsToCaffeineMCRepository